### ISSUE TITLE
fetchMultiple does not batch requests that use FormData

### ISSUE THREAD

**Issue by easdasd** [daohoangson/js-tinhte-api#5]
## Summary
`api.batch` does not seem to work properly when the requests use formData

### Example usage:
```javascript
    ...
    // allFiles is an array of 2 objects, each object has the field `raw` containing the file data
    const fetches = [];
    const uri = 'posts/attachments';
    const fetch = (file) => {
      const formData = new window.FormData();
      // formData.append('post_id', postId);
      formData.append('post_id', 51599657);
      formData.append('file', file.raw);
      const promise = this.api.post({ uri, body: formData });
      fetches.push(promise);
    };
    return this.api.batch(() => allFiles.map(fetch))
      .then(() => Promise.all(fetches))
      .catch((err) => {
        console.log(err);
        this.deleteAttachments(uploadedAttachments, forumId);
        throw err;
      });
```

### Expected Behaviour:
The POST requests are batched

### Actual Behaviour:
The 2 POST requests (for 2 files) are sent individually.  
While both requests return success result, the api raises error `There is no fetches`.
![image](https://user-images.githubusercontent.com/15865062/40873216-a0c25174-6686-11e8-8f11-cba3553bb0b9.png)

**Comment by easdasd** [comment]
How about the error `There is no fetches` anh? Can it be safely ignored?

**Comment by daohoangson** [comment]
Well, all sub requests are fetched by themselves so there is nothing in the
batch. In this case, it can be ignored.

**Comment by daohoangson** [comment]
Is it okie to close this issue now, @easdasd?

**Comment by easdasd** [comment]
okay.
