### ISSUE TITLE
React Tree Walker is not compatible with React Native

### ISSUE THREAD

**Issue by duyluandethuong** [daohoangson/js-tinhte-api#9]
Run tinhte-api on Android, an error pops up:

```
@@for is not a function (evaluating '(typeof Symbol === "function" ? Symbol.for : "@@for")('react.forward_ref')')
```

The first error lines reads: 

```
<unknow>
react-tree-walker.js:14:34

<unknow>
fetchApiDataForProvider:5:4
```

**Comment by daohoangson** [comment]
https://stackoverflow.com/questions/45675766/for-is-not-a-function-evaluating-typeof-symbol-function-symbol-for seems to have a good enough workaround.
